// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: feeds.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const claimFeedsToFetch = `-- name: ClaimFeedsToFetch :many
WITH due AS (
    SELECT id FROM feeds
    WHERE next_fetch_at IS NULL OR next_fetch_at <= NOW()
    ORDER BY last_fetched_at ASC NULLS FIRST
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
UPDATE feeds
SET last_fetched_at = NOW(), updated_at = NOW()
FROM due
WHERE feeds.id = due.id
RETURNING feeds.id, feeds.created_at, feeds.updated_at, feeds.name, feeds.url, feeds.user_id, feeds.last_fetched_at, feeds.etag, feeds.last_modified, feeds.failure_count, feeds.last_error, feeds.next_fetch_at
`

// Atomically claims up to N due feeds. FOR UPDATE SKIP LOCKED in a
// materialized CTE lets several aggregator processes run at once without
// fetching the same feed twice. All times come from the database clock.
func (q *Queries) ClaimFeedsToFetch(ctx context.Context, batchSize int32) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, claimFeedsToFetch, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Url,
			&i.UserID,
			&i.LastFetchedAt,
			&i.Etag,
			&i.LastModified,
			&i.FailureCount,
			&i.LastError,
			&i.NextFetchAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createFeed = `-- name: CreateFeed :one
INSERT INTO feeds (id, created_at, updated_at, name, url, user_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, created_at, updated_at, name, url, user_id, last_fetched_at, etag, last_modified, failure_count, last_error, next_fetch_at
`

type CreateFeedParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Url       string
	UserID    uuid.UUID
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, createFeed,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.Url,
		arg.UserID,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Url,
		&i.UserID,
		&i.LastFetchedAt,
		&i.Etag,
		&i.LastModified,
		&i.FailureCount,
		&i.LastError,
		&i.NextFetchAt,
	)
	return i, err
}

const deleteFeed = `-- name: DeleteFeed :exec
DELETE FROM feeds WHERE id = $1 AND user_id = $2
`

type DeleteFeedParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteFeed(ctx context.Context, arg DeleteFeedParams) error {
	_, err := q.db.ExecContext(ctx, deleteFeed, arg.ID, arg.UserID)
	return err
}

const getFeedByURL = `-- name: GetFeedByURL :one
SELECT id, created_at, updated_at, name, url, user_id, last_fetched_at, etag, last_modified, failure_count, last_error, next_fetch_at FROM feeds WHERE url = $1
`

func (q *Queries) GetFeedByURL(ctx context.Context, url string) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeedByURL, url)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Url,
		&i.UserID,
		&i.LastFetchedAt,
		&i.Etag,
		&i.LastModified,
		&i.FailureCount,
		&i.LastError,
		&i.NextFetchAt,
	)
	return i, err
}

const getFeeds = `-- name: GetFeeds :many
SELECT id, created_at, updated_at, name, url, user_id, last_fetched_at, etag, last_modified, failure_count, last_error, next_fetch_at FROM feeds
`

func (q *Queries) GetFeeds(ctx context.Context) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, getFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Url,
			&i.UserID,
			&i.LastFetchedAt,
			&i.Etag,
			&i.LastModified,
			&i.FailureCount,
			&i.LastError,
			&i.NextFetchAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeedsWithUser = `-- name: GetFeedsWithUser :many
SELECT 
    feeds.id, feeds.created_at, feeds.updated_at, feeds.name, feeds.url, feeds.user_id, feeds.last_fetched_at, feeds.etag, feeds.last_modified, feeds.failure_count, feeds.last_error, feeds.next_fetch_at,
    users.name as user_name
FROM feeds
JOIN users ON feeds.user_id = users.id
WHERE feeds.user_id = $1
`

type GetFeedsWithUserRow struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Name          string
	Url           string
	UserID        uuid.UUID
	LastFetchedAt sql.NullTime
	Etag          sql.NullString
	LastModified  sql.NullString
	FailureCount  int32
	LastError     sql.NullString
	NextFetchAt   sql.NullTime
	UserName      string
}

func (q *Queries) GetFeedsWithUser(ctx context.Context, userID uuid.UUID) ([]GetFeedsWithUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getFeedsWithUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeedsWithUserRow
	for rows.Next() {
		var i GetFeedsWithUserRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Url,
			&i.UserID,
			&i.LastFetchedAt,
			&i.Etag,
			&i.LastModified,
			&i.FailureCount,
			&i.LastError,
			&i.NextFetchAt,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordFeedFailure = `-- name: RecordFeedFailure :one
UPDATE feeds
SET failure_count = failure_count + 1,
    last_error = $1,
    next_fetch_at = NOW() + make_interval(secs => $2::float8),
    updated_at = NOW()
WHERE id = $3
RETURNING failure_count
`

type RecordFeedFailureParams struct {
	LastError      sql.NullString
	BackoffSeconds float64
	ID             uuid.UUID
}

func (q *Queries) RecordFeedFailure(ctx context.Context, arg RecordFeedFailureParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, recordFeedFailure, arg.LastError, arg.BackoffSeconds, arg.ID)
	var failure_count int32
	err := row.Scan(&failure_count)
	return failure_count, err
}

const recordFeedSuccess = `-- name: RecordFeedSuccess :exec
UPDATE feeds
SET etag = $2, last_modified = $3, failure_count = 0, last_error = NULL, next_fetch_at = NULL, updated_at = NOW()
WHERE id = $1
`

type RecordFeedSuccessParams struct {
	ID           uuid.UUID
	Etag         sql.NullString
	LastModified sql.NullString
}

func (q *Queries) RecordFeedSuccess(ctx context.Context, arg RecordFeedSuccessParams) error {
	_, err := q.db.ExecContext(ctx, recordFeedSuccess, arg.ID, arg.Etag, arg.LastModified)
	return err
}
